# frozen_string_literal: true
require 'cloud_foundry/rake'

organization 'webservices' do |t|
  t.name = 'XMLSOA'
end

domain 'ws.uhlig.it', 'XMLSOA'

desc 'Target our org'
task debug: ['webservices'] do |t|
  puts `cf target -o XMLSOA` # note that we cannot use the webservices => XMLSOA indirection here
end

# TODO
# space 'webservices', 'XMLSOA'
